### ISSUE TITLE
verify_deployed.py failed on farmer

### ISSUE THREAD

**Issue by zhangweis** [muesliswap/muesliswap-core#1]
I compiled muesliswap-farming by using "npm run compile".
I run by "python3 verify_deployed.py" and got :
```
[OK] Contract 'factory' deployed in tx 0x189339b4c82cd6b6d9d78f62bc21eacb4077ab280083630a853e97b8eaf8167a matches with ./build/MuesliFactory.json
[OK] Contract 'router' deployed in tx 0xa2a6a54e855699a0fc2ba226baf580668a83ecb2123649d2a53fd00a6095b986 matches with ../muesliswap-periphery/build/MuesliRouter.json
[ERR] Contract 'farmer' deployed in tx 0x028a6a890d38dfb316d2e390fed0e019ca04b82387933c729efe81b9cc26426d doesn't match with ../muesliswap-farming/build/contracts/MasterFarmer.json !
```
I tried on commits "0b8f2ca0d8ecb1f77b007de63956a880b708d0d4" and "190c976e35131ec1489c09587924f6a574340975" with no luck. Commit "02733b203081281e16bc4721662e00de7448d15b" doesn't compile.

Reply from tg:
Here the thing is factory and router were deployed directly from the repo, but farming was deployed from remix because we wanted to launch it immediately after the presale. Apparently there's a few bytes "metadata" that are different based on the IDE and these don't match when you compile it again. But these shouldn't be compared by the script anyway. What command did you use to compile? The correct compiler version and optimization runs are written in truffle-config

I guess the script needs to change or better we can have a special muesliswap-farming branch for deployed farm contract.

**Comment by zhangweis** [comment]
btw, on 0b8f2ca0d8ecb1f77b007de63956a880b708d0d4 I have to run "rm contracts/Presale.sol" to pass compilation or I'll get following:
```
project:/contracts/Presale.sol:1:1: ParserError: Source file requires different compiler version (current compiler is 0.6.12+commit.27d51765.Emscripten.clang) - note that nightly builds are considered to be strictly less than the released version
pragma solidity ^0.8.9;
^---------------------^

Error: Truffle is currently using solc ^0.6.12, but one or more of your contracts specify "pragma solidity ^0.8.9".
```

**Comment by MuesliSwapTeam** [comment]
Hi,sorry for the late reply. We updated some configurations and now it should work. Could you try downloading the farming repository again and rerun the script. Does it now work for you?

**Comment by zhangweis** [comment]
Thanks for the update. It works now and all 3 contracts are "[OK]" now.
